spring:
  cloud:
    gateway:
      # 서비스 디스커버리를 통한 동적 라우트 생성
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true   # 서비스아이디 소문자화
          predicate: Path=/services/**  # optional: 디스커버리 기본 predicate
      # 정적 라우트 예시 (디스커버리와 병행 사용 가능)
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/v1/product/**
          filters:
            - "RewritePath=/v1/product/(?<path>.*), /${path}"
            - name: AddRequestHeader
              args:
                X-From-Gateway: my-gateway
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/v1/order/**
          filters:
            - "RewritePath=/v1/order/(?<path>.*), /${path}"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  endpoint:
    gateway:
      enabled: true