spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false # Netflix Ribbon 대신 Spring Cloud LoadBalancer 사용


management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,prometheus
  endpoint:
    prometheus:
      enabled: true